# Generated by Django 2.2.5 on 2020-04-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('age', models.DateTimeField()),
                ('weight', models.SmallIntegerField()),
            ],
        ),
    ]
