# Generated by Django 2.2.5 on 2020-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='catprofile',
            name='birth',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='catprofile',
            name='gender',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='catprofile',
            name='image',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
