# Generated by Django 2.2.5 on 2020-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0002_auto_20200425_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catprofile',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='catprofile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
