# Generated by Django 2.2.5 on 2020-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0004_auto_20200425_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catprofile',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
