# Generated by Django 2.2.5 on 2020-04-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0005_auto_20200426_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalColoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='catprofile',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheerjoy.AnimalColoration'),
        ),
    ]
