# Generated by Django 2.2.5 on 2020-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0006_auto_20200426_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
    ]
