# Generated by Django 2.2.5 on 2020-04-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0009_auto_20200426_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cultures',
            new_name='Culture',
        ),
        migrations.RenameModel(
            old_name='Litters',
            new_name='Litter',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='animalcoloration',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catprofile',
            name='father',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impregnated', to='sheerjoy.CatProfile'),
        ),
        migrations.AlterField(
            model_name='catprofile',
            name='mother',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born', to='sheerjoy.CatProfile'),
        ),
    ]
