# Generated by Django 2.2.5 on 2020-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0011_auto_20200428_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
