# Generated by Django 2.2.5 on 2020-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0012_auto_20200430_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
