# Generated by Django 2.2.5 on 2020-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0013_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='who_is_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='on_picture', to='sheerjoy.CatProfile'),
        ),
    ]
