# Generated by Django 2.2.5 on 2020-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0014_gallery_who_is_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.ManyToManyField(related_name='photos', to='sheerjoy.HashTag'),
        ),
    ]
