# Generated by Django 2.2.5 on 2020-05-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0015_auto_20200501_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='photos', to='sheerjoy.HashTag'),
        ),
    ]
