# Generated by Django 3.0.6 on 2020-06-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0019_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
