# Generated by Django 3.0.6 on 2020-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheerjoy', '0020_optional_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_min',
            field=models.ImageField(default=None, upload_to='gallery/'),
        ),
    ]
